### ISSUE TITLE
Geocoding API via address field

### ISSUE THREAD

**Issue by ghost** [OblikStudio/kirby-simplemap-field#1]
Thank you very much for this new field. Works like a charm and integrates very well. 👍

I wanted to ask if you plan to add an address field so we can use the Geocoding API like in kirby-map-field?

Best regards 
Mike

**Comment by yandodov** [comment]
When I have some more time, I can add it, sure thing! I want to see how much attention this plugin gets.

My goal with this field is to have the simplest map ever and any functionality on top to be a bonus. I have plans to add latitude/longitude/zoom fields, address field, and options for the placement of all that. If there’s demand, I’ll deliver!

**Comment by medienbaecker** [comment]
It's really a very well made field. I just tested it and replaced the kirby-map-field by August Miller on several websites.

An address field would be awesome!
